apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-m8t-io-tls
spec:
  secretName: k8s-m8t-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.m8t.io
  dnsNames:
    - k8s.m8t.io
    - www.k8s.m8t.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.m8t.io
          - www.k8s.m8t.io

